### ISSUE TITLE
Incompatibility with TimeCapsule

### ISSUE THREAD

**Issue by fkuehne** [videolabs/libdsm#43]
TimeCapsule is a NAS manufactured by Apple mainly designed to have a network server for Macs to backup their data.

However, it is running an old version of smbx and while libdsm successfully logs in, there is never a directory listing. Reasons are unknown for now.

**Comment by jbkempf** [comment]
Wireshark trace would be nice.
Asking @sylverb also.

**Comment by sylverb** [comment]
I have an Airport Extreme which is almost the same than a time capsule (the main difference is that there is an internal hdd in the time capsule and you have to plug an USB disk on the Airport Extreme). I did some tests quickly with no issues but there are 3 "authentication" methods available on the Time Capsule and I did not test all !
@fkuehne , which one are you using ?

**Comment by fkuehne** [comment]
Looks like both the A1470 (5th gen, Mid-2013) and the A1355 (3rd gen, late 2009).

**Comment by sylverb** [comment]
I've made some additional tests on my Airport Extreme :
If I set "Disk Access" mode to "With account", then everything works well !
If I set "Disk Access" mode to "With a disk password" or to "With device password", the authentication seems to be OK (If I set right password it pass the authentication part, and if I set a wrong password it fails), but the shares listing is failing !
After investigating this, I found out that the Shares listing if failing because the AirPort extreme is returning a "tid" of 0, but libdsm is considering that a tid of 0 is not valid (tid is returned by smb_tree_connect function) ... If I remove asserts & checks about tid not being 0, everything works well ...
I'm not sure of what is the best correction ... changing the "not valid" value of tid to -1 (but it requires to change the type of tid from uint16_t to something a signed 32 bits) of simply add this check for smb_tree_connect returned value, and remove all the asserts about tid not being null ... Any advices ?

**Comment by jbkempf** [comment]
As you prefer, I'd say move to signed and check about -1.

**Comment by sylverb** [comment]
@fkuehne please tell us if it corrects your issue with time capsule !

**Comment by fkuehne** [comment]
> On 29 Nov 2015, at 16:10, Sylver Bruneau <notifications@github.com> wrote:
> 
> @fkuehne please tell us if it corrects your issue with time capsule !

I don’t have such a device, but I’ll ask our testers as soon as we push the next beta shortly :)

Thanks for investigating this!

**Comment by jbkempf** [comment]
Please check that it works now.

**Comment by sylverb** [comment]
I've just received a feedback from a user with a TimeCapsule that is reporting that my latest build including this correction is solving his connection issue with his TimeCapsule !

**Comment by fkuehne** [comment]
Amazing!

Updated VLC-TV beta is on its way ;)

**Comment by fkuehne** [comment]
Fix confirmed by VLC users, too.
