### ISSUE TITLE
Can't build on OS X for iOS

### ISSUE THREAD

**Issue by macropa** [videolabs/libdsm#91]
Hi,

I'm having some trouble cross compiling libdsm for arm (iOS).  My first thought was that it was a generic problem with what I was doing, rather than something directly related to libdsm, but now I'm wondering if it's something libdsm specific.  I posted the details on [stackoverflow](http://stackoverflow.com/questions/38836754/cant-cross-compile-c-library-for-arm-ios).  If VNC for iOS uses this library, though, then it must work.  Does anyone know what might be wrong, and is it my problem, of a libdsm issue?

Thanks.

**Comment by chouquette** [comment]
Disclaimer: I don't know much about building on/for macOS/iOS. However, setting -arch in your CFLAGS/LDFLAGS seems like an awful idea. Please use configure's --host parameter to target a specific architecture.
I have no idea about the triplet that you need to use, but I'm sure you can find it by fiddling in the various VLC build script for Apple platforms.

In any case, this is not a libdsm issue, since you are not getting to the actual build stage, but fail during configure.

**Comment by macropa** [comment]
Thanks for your response.  Good idea - I'll go look for the VLC build scripts.
